version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    restart: unless-stopped
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
      - 127.0.0.1:8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/dynamic:/etc/traefik/dynamic
      - ./services/traefik/certs:/etc/traefik/certs

  portainer:
    image: portainer/portainer-ce:2.5.1-alpine
    restart: unless-stopped
    command:
      - "-H"
      - "unix:///var/run/docker.sock"
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:8025:8025
      - 127.0.0.1:1025:1025
    networks:
      mailhog:
        aliases:
          - mailhog

  kolombo:
    build:
      context: ./services/kolombo
      dockerfile: ./Dockerfile
    networks:
      kolombo:
        aliases:
          - kolombo
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=Host(`kolombo.pro.test`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.middlewares=secure-headers@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true"
    environment:
      KOLOMBO_VAPID_PUBLIC_KEY: "${KOLOMBO_VAPID_PUBLIC_KEY}"
      KOLOMBO_VAPID_PRIVATE_KEY: "${KOLOMBO_VAPID_PRIVATE_KEY}"
      KOLOMBO_SUBSCRIPTION: "${KOLOMBO_SUBSCRIPTION}"
    volumes:
      - ./services/traefik/certs:/etc/certs/custom

networks:
  web:
    external: true
  mailhog:
    external: true
  kolombo:
    external: true

volumes:
  portainer-data:
