services:
  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
      - 127.0.0.1:8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/traefik.yaml:/traefik.yaml
      - ./services/traefik/dynamic:/dynamic
      - ./services/traefik/certs/output:/certs

  portainer:
    image: portainer/portainer-ce:2.24.1-alpine
    restart: unless-stopped
    command:
      - "-H"
      - "unix:///var/run/docker.sock"
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  localstack:
    image: localstack/localstack:4.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.localstack.rule=Host(`localstack.pro.test`)"
      - "traefik.http.services.localstack.loadbalancer.server.port=4566"
      - "traefik.http.routers.localstack.entrypoints=websecure"
      - "traefik.http.routers.localstack.tls=true"
    environment:
      - PERSISTENCE=1
    networks:
      - localstack
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack

networks:
  web:
    external: true
  localstack:
    external: true

volumes:
  portainer-data:
  localstack-data: