version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
      - 127.0.0.1:8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/traefik.yaml:/traefik.yaml
      - ./services/traefik/dynamic:/dynamic
      - ./services/traefik/certs/output:/certs

  portainer:
    image: portainer/portainer-ce:2.5.1-alpine
    restart: unless-stopped
    command:
      - "-H"
      - "unix:///var/run/docker.sock"
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

networks:
  web:
    external: true
  mailhog:
    external: true

volumes:
  portainer-data:
